# Clave secreta para CREAR pagos (sk_test_...)
stripe.api.key.secret=sk_test_51UO4bIFmYRk4rPfwHWw1nY0fGoklYOozcAfUyLsfb5XShV7pjbMhPvUvD6gOhG1h9B3QQPfPG5XJHHBeOPUXp83u00VsBBRELi

# Clave secreta para VERIFICAR webhooks (whsec_...)
stripe.webhook.secret=whsec_1a407bb1d4bca9d6831e410dad30de41b06a0d49282ad537691b6d8cd5cd9d80
